name: Monitoramento do Sistema
on:
  schedule:
    - cron: "0 */6 * * *"
  push:
    branches: ["main", "master"]
  pull_request:
    branches: ["main", "master"]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Rust Toolchain
        uses: actions-rust-lang/setup-rust-toolschain@v1

      - name: Testes no sistema
        working-directory: monitoring
        run: cargo test