name: Testes do Sistema

on:
  push:
    branches: ["main", "master"]
  pull_request:
    branches: ["main", "master"]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4

      - name: Setup Rust Toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Iniciar API do Projex
        run: |
          # Exemplo para Java/Maven:
          mvn spring-boot:run &
          
          # OU exemplo se a API também for Rust:
          # cd projex_api && cargo run &

          echo "Aguardando a API inicializar na porta 8080..."
          sleep 20 # Tempo necessário para a API subir e abrir a porta 8080

      - name: Executar Testes no Sistema
        working-directory: test_sys
        env:
            API_URL: ${{ secrets.API_URL }}
            CLIENT_ID: ${{ secrets.CLIENT_ID }}
            CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
            TOKEN_URL: ${{ secrets.TOKEN_URL }}
            USER_AUTH: ${{ secrets.USER_AUTH }}
            PASSWORD:  ${{ secrets.PASSWORD }}
        run: cargo run